### ISSUE TITLE
Faster display update ideas

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [python-ugame/circuitpython-stage#1]
This looks fantastic! Insta-ordered when I saw it on Tindie.

Have you thought about how to speed up writes to the display? I was [experimenting with a Teensy 3.6 and an ILI9341](https://www.youtube.com/watch?v=RK0VyQ14qFc) and came up with a few ideas.

1. **Increase SPI bus speed**
   I'm not sure what is possible here. I've never used the ATSAMD21 or Circuit/MicroPython yet. It looks like the speed is defined here? https://github.com/python-ugame/circuitpython/blob/master/ports/atmel-samd/asf4_conf/samd21/hpl_sercom_config.h#L55 And that it's set to 50000 (50kHz). Could this be raised to 12000000 (12MHz)? Though ATSAMD21 data sheet says SPI can run at up to half of CPU clock speed (24MHz) 
1. **Reduce color depth**
   The ST7735 can accept 12bits per pixel (page 48 on the data sheet). That would reduce the total amount of data needed to be sent and would still provide plenty of colors for games.

1. **Use a framebuffer**
   Storing a frame buffer in RAM would let you have all draw operations modify the buffer only. Then the whole buffer could just be written out to the display. A 128x128 buffer at 12bits per pixel would take up 24k of ram which may be too much. 
      1. **Framebuffer with a color palette**
         Another option is to pick a color pallete like [pico8](https://www.lexaloffle.com/pico-8.php) or [DawnBringer](https://github.com/geoffb/dawnbringer-palettes/) palletes and store indexes into the pallete as the framebuffer. Each pixel could then be a single byte and 128x128 buffer would use 16k of ram.
      1. **1/2 resolution framebuffer**
         64x64 resolution would probably still work well for many games and be more readable. In [this video](https://www.youtube.com/watch?v=RK0VyQ14qFc) I'm using a 160x120 framebuffer on a 320x240 screen and it still looks nice. For 12bits per pixel this would use 6k of RAM. For indexed colors (8bits per pixel) it would use 4k of RAM. [Here](https://github.com/AnthonyDiGirolamo/ILI9341_t3n/commit/674eb0414360390b26fc4e8ab04a4717d0b8819b) is how I did this on the ILI9341. Basically just write each pixel in the framebuffer twice and then each row twice. This effectively doubles the pixel size. 

1. **Use DMA to send SPI data**
   This would provide async display updates and let the CPU do more work while the display is updating. It would probably require [writing a module with C](http://micropython-dev-docs.readthedocs.io/en/latest/adding-module.html) that uses DMA to output a framebuffer stored in RAM to the display. The framebuffer would have to be full resolution and not indexed colors and thus require at least 24k of RAM I think. I'm not sure how to get started with this but found an example of how to do it in C here: https://github.com/adafruit/Adafruit_ZeroDMA/blob/master/examples/zerodma_spi2/zerodma_spi2.ino

I'll definitely be trying some of these when my µGame 10 arrives. Thanks for creating it!

**Comment by jellonek** [comment]
I believe that first one is already set to 8MHz (i'm not sure why not to 12MHz, idk what is `Salae`) [there]( https://github.com/python-ugame/circuitpython/blob/master/ports/atmel-samd/boards/ugame10/mpconfigboard.h#L4).

**Comment by deshipu** [comment]
First of all, I'm really sorry for the late answer, I forgot to watch this repository and I didn't get a notification for the bug. I have now fixed that, so I will get notifications in the future.

@AnthonyDiGirolamo thank you for your ideas. I'm certainly working on getting things faster, and I have already considered a lot of your suggestions.

1. I'm setting the SPI peripheral explicitly to 24MHz in the `ugame.py`. That is the maximum SAMD21 can do. The display itself works up to 40MHz (though the spec says ~20MHz IIRC).

2. It's tricky to send 12 bits per pixel — my experience with working on FAT12 shows that sending those extra 4 bits might actually be faster in the end.

3i. I'm already using color palettes for all the sprites and tiles — that's the only way they fit in memory in the first place.

3ii. I really want to have 16×16 sprites, because it's really hard to draw a meaningful animated character in less. And 4×4 tiles on the screen would be a bit too claustrophobic. Also, I still need to send all those pixels to the display, so it doesn't help much.

4. CircuitPython's SPI drivers already use DMA, with a 512 byte buffer.

@jellonek that is the other SPI peripheral, the one that is used to communicate with the flash memory chip. It has no impact on the speed of display updates.

Having said that, I think there is still some room for improvement there. I have recently made a small fix that should speed up sprite updates a little, and I think I could optimize the C code that does rendering a little better. If you want to look at it, it's mostly in https://github.com/python-ugame/circuitpython/blob/ugame10/shared-module/_stage/__init__.c#L34 and https://github.com/python-ugame/circuitpython/blob/ugame10/shared-module/_stage/Layer.c#L32
